name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn --production=false
      - name: Lint
        run: yarn lint
      - name: Build
        env:
          NODE_PATH: src
          NODE_ENV: production
          REACT_APP_PROTOCOL: https
          REACT_APP_ENV: production
          REACT_APP_PORT: "443"
          GENERATE_SOURCEMAP: "false"
          FRONTEND_DISTRIBUTION_ID: ${{ secrets.FRONTEND_DISTRIBUTION_ID }}
          FRONTEND_S3_BUCKET: ${{ secrets.FRONTEND_S3_BUCKET }}
          REACT_APP_GA_TRACKING_ID: ${{ secrets.REACT_APP_GA_TRACKING_ID }}
          REACT_APP_GITHUB_CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          REACT_APP_HOST: ${{ secrets.REACT_APP_HOST }}
          REACT_APP_VAPID_PUBLIC: ${{ secrets.REACT_APP_VAPID_PUBLIC }}
          REACT_APP_CAPTCHA_SITE: ${{ secrets.REACT_APP_CAPTCHA_SITE }}
        run: yarn run build
      - name: Export Branch Name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Upload artifact
        if: ${{ github.event_name == 'push' && env.BRANCH_NAME == 'main' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: "build"
  deploy:
    name: "Deploy"
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    needs: [build]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Export Branch Name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Setup Pages
        if: ${{ env.BRANCH_NAME == 'main' }}
        uses: actions/configure-pages@v2
      - name: Deploy to GitHub Pages
        if: ${{ env.BRANCH_NAME == 'main' }}
        id: deployment
        uses: actions/deploy-pages@v1
