name: CI
on:
  push:
    branches:
    - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Dependencies
      run: yarn
    - name: Build
      env:
        NODE_PATH: src
        NODE_ENV: production
        REACT_APP_PROTOCOL: https
        REACT_APP_ENV: production
        REACT_APP_PORT: '443'
        GENERATE_SOURCEMAP: 'false'
        FRONTEND_DISTRIBUTION_ID: ${{ secrets.FRONTEND_DISTRIBUTION_ID }}
        FRONTEND_S3_BUCKET: ${{ secrets.FRONTEND_S3_BUCKET }}
        REACT_APP_GA_TRACKING_ID: ${{ secrets.REACT_APP_GA_TRACKING_ID }}
        REACT_APP_GITHUB_CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
        REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
        REACT_APP_HOST: ${{ secrets.REACT_APP_HOST }}
        REACT_APP_VAPID_PUBLIC: ${{ secrets.REACT_APP_VAPID_PUBLIC }}
        REACT_APP_CAPTCHA_SITE: ${{ secrets.REACT_APP_CAPTCHA_SITE }}
      run: yarn run build
    - name: Extract Tag
      run: bash .github/get_tag.sh
    - name: Configure AWS Credentials
      if: ${{ github.event_name == 'push' && startsWith(env.TAG, 'v') }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Deploy to S3
      if: ${{ github.event_name == 'push' && startsWith(env.TAG, 'v') }}
      env:
        AWS_PAGER: ''
      run: |
        cd build;
        aws s3 sync --delete . s3://${{ secrets.FRONTEND_S3_BUCKET }}
        aws cloudfront create-invalidation --distribution-id ${{ secrets.FRONTEND_DISTRIBUTION_ID }} --paths /index.html /manifest.json
        