name: Go into Maintenance
on:
  workflow_dispatch:
jobs:
  deploy_maintenance:
    name: "Deploy Maintenance"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Step into Maintenance
      run: |
        aws s3 cp ./maintenance.html s3://${{ secrets.FRONTEND_S3_BUCKET }}/index.html
        aws cloudfront create-invalidation --distribution-id ${{ secrets.FRONTEND_DISTRIBUTION_ID }}
